import React, { useState, useEffect } from "react";
import { motion } from "framer-motion";

export default function News() {
  const [token, setToken] = useState("");
  const [news, setNews] = useState("");

  useEffect(() => {
    async function getUser() {
      const token = localStorage.getItem("token");
      setToken(token);
      try {
        const options = {
          method: "GET",
          headers: {
            "X-RapidAPI-Key":
              "2be1de11d0msh58feda7445d3b54p1b9fdbjsne738a62ed5e4",
            "X-RapidAPI-Host":
              "bloomberg-market-and-financial-news.p.rapidapi.com",
          },
        };

        let response = await fetch(
          "https://bloomberg-market-and-financial-news.p.rapidapi.com/news/list?id=markets",
          options
        );
        const data = await response.json();
        setNews(data);
      } catch (err) {
        console.error(err);
      }
    }
    getUser();
  }, []);

  const containerVariants = {
    hidden: { opacity: 0, y: 20 },
    visible: { opacity: 1, y: 0, transition: { delay: 0.5, duration: 0.5 } },
  };

  return (
    <div className="p-5">
      <h1>NEWS</h1>

      <motion.div
        variants={containerVariants}
        initial="hidden"
        animate="visible"
        className="conatiner mt-3 p-3 shadow-lg"
        style={{ backgroundColor: "lightcyan", borderRadius: "10px" }}
      >
        {news?.modules && (
          <div className="row">
            <h3>{news.modules[2].stories[3].title}</h3>
            <div className="col-lg-7">
              <p>{news.modules[2].stories[3].byline}</p>

              <p>{news.modules[2].stories[3].autoGeneratedSummary}</p>
            </div>
            <div className="col-lg-5 p-2">
              <a href={news.modules[2].stories[3].shortURL}>
              <img className="shadow-lg"
                src={news.modules[2].stories[3].thumbnailImage}
                alt=""
                style={{ width: "30vh", borderRadius: "10px" }}
              />
              </a>
            </div>
          </div>
        )}
      </motion.div>

      <motion.div
        variants={containerVariants}
        initial="hidden"
        animate="visible"
        className="conatiner mt-3 p-3 "
        style={{ backgroundColor: "lightcyan", borderRadius: "10px" }}
      >
        {news?.modules && (
          <div className="row">
            <h3>{news.modules[2].stories[0].title}</h3>
            <div className="col-lg-7">
              <p>{news.modules[2].stories[0].byline}</p>

              <p>{news.modules[2].stories[0].autoGeneratedSummary}</p>
            </div>
            <div className="col-lg-5 p-2">
              <a href={news.modules[2].stories[0].shortURL}>
              <img 
                src={news.modules[2].stories[0].thumbnailImage}
                alt=""
                style={{ width: "30vh", borderRadius: "10px" }}
              />
              </a>
            </div>
          </div>
        )}
      </motion.div>

      <motion.div
        variants={containerVariants}
        initial="hidden"
        animate="visible"
        className="conatiner mt-3 p-3 "
        style={{ backgroundColor: "lightcyan", borderRadius: "10px" }}
      >
        {news?.modules && (
          <div className="row">
            <h3>{news.modules[2].stories[2].title}</h3>
            <div className="col-lg-7">
              <p>{news.modules[2].stories[2].byline}</p>

              <p>{news.modules[2].stories[2].autoGeneratedSummary}</p>
            </div>
            <div className="col-lg-5 p-2">
              <a href={news.modules[2].stories[2].shortURL}>
              <img
                src={news.modules[2].stories[2].thumbnailImage}
                alt=""
                style={{ width: "30vh", borderRadius: "10px" }}
              />
              </a>
            </div>
          </div>
        )}
      </motion.div>
    </div>
  );
        }
